config/routes.rb
DataQualityCollector::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post "filter/set"
  resources :subjective_assessment_surveys

  resources :values

  resources :metric_values

  resources :dimension_values

  resources :app_values

  resources :metrics

  resources :dimensions

  resources :data_assets

  resources :apps

  root :to => "apps#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/data_asset.rb
class DataAsset < ActiveRecord::Base
  belongs_to :app
  has_and_belongs_to_many :metrics
  has_many :rollups, :dependent => :destroy

  include Calculations
  include Charting
  include Rollups

  def score(stamp)
    average metrics.map{|metric| metric.score(stamp)}
  end

  def current_score
    return 0.0 if metrics.empty?
    average metrics.map{|metric| metric.current_value}
  end

  #Some stuff to make it quack like a Dimension
  def expectation_met?(*args)
    true
  end
  def expectation
    0.5
  end

end

app/controllers/data_assets_controller.rb
class DataAssetsController < ApplicationController
  before_action :set_data_asset, only: [:show]

  # GET /data_assets
  # GET /data_assets.json
  def index
    @data_assets = DataAsset.all
  end

  # GET /data_assets/1
  # GET /data_assets/1.json
  def show
    @dimension = @data_asset
    render 'dimensions/show'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_asset
      @data_asset = DataAsset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def data_asset_params
      params.require(:data_asset).permit(:name, :description, :app_id)
    end
end

app/views/data_assets/index.html.haml
%h1 Listing data_assets

%table
  %thead
    %tr
      %th Name
      %th Description
      %th App
      %th

  %tbody
    - @data_assets.each do |data_asset|
      %tr
        %td= data_asset.name
        %td= data_asset.description
        %td= data_asset.app
        %td= link_to 'Show', data_asset

app/views/data_assets/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @data_asset.name
%p
  %b Description:
  = @data_asset.description
%p
  %b App:
  = @data_asset.app

= link_to 'Edit', edit_data_asset_path(@data_asset)
\|
= link_to 'Back', data_assets_path