config/routes.rb
DataQualityCollector::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post "filter/set"
  resources :subjective_assessment_surveys

  resources :values

  resources :metric_values

  resources :dimension_values

  resources :app_values

  resources :metrics

  resources :dimensions

  resources :data_assets

  resources :apps

  root :to => "apps#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Twitter Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Twitter Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "DQ-collector (#{APP_VERSION})", root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li= link_to "Apps", apps_path

- if user_signed_in?
  %li= link_to 'Account', edit_user_registration_path
- else
  %li= link_to 'Account', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Data Quality Collector'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Data Quality Collector'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'partials/resolution_and_time_filter'
      = render 'layouts/messages'
      .container= yield